### ISSUE TITLE
TODO - Transform into a full backend

### ISSUE THREAD

**Issue by Jon-Ledo** [Jon-Ledo/SQL-Express-Instagram-Data-Practise#2]
- [ ] Require Express, MySql2, dotenv, Sequelize
- [ ] Create Model
- [ ] Create DB connection
- [ ] Set up routes 
- [ ] Clean server.js
