### ISSUE TITLE
TODO - Create simple front end

### ISSUE THREAD

**Issue by Jon-Ledo** [Jon-Ledo/SQL-Express-Instagram-Data-Practise#3]
- [ ] Simple front end that grabs data and puts onto screen
- [ ] public folder
- [ ] use.static 
- [ ] basic html/css/js structure
- [ ] must interact with the backend
